### ISSUE TITLE
The extra modules are not being installed

### ISSUE THREAD

**Issue by yuri2000** [drachtio/ansible-role-fsmrf#6]
The extra modules are not being installed with this version of the ansible-role-fsmrf.

During the playbook run all looks fine:

TASK [ansible-role-fsmrf : include_tasks] **************************************
included: /etc/ansible/roles/ansible-role-fsmrf/tasks/extra.yml for freeswitch-mrf-02

TASK [ansible-role-fsmrf : copy modules into place] ****************************
changed: [freeswitch-mrf-02] => (item={u'dest': u'/usr/local/src/freeswitch//src/mod/applications/', u'src': u'/usr/local/src/drachtio-freeswitch-modules/modules/mod_google_transcribe/'})
changed: [freeswitch-mrf-02] => (item={u'dest': u'/usr/local/src/freeswitch//src/mod/applications/', u'src': u'/usr/local/src/drachtio-freeswitch-modules/modules/mod_google_tts/'})
changed: [freeswitch-mrf-02] => (item={u'dest': u'/usr/local/src/freeswitch//src/mod/applications/', u'src': u'/usr/local/src/drachtio-freeswitch-modules/modules/mod_dialogflow/'})
changed: [freeswitch-mrf-02] => (item={u'dest': u'/usr/local/src/freeswitch//src/mod/applications/', u'src': u'/usr/local/src/drachtio-freeswitch-modules/modules/mod_aws_transcribe/'})

TASK [ansible-role-fsmrf : copy Makefile.am, configure.ac etc into place] ******
changed: [freeswitch-mrf-02] => (item={u'dest': u'/usr/local/src/freeswitch//configure.ac', u'src': u'configure.ac.extra'})
changed: [freeswitch-mrf-02] => (item={u'dest': u'/usr/local/src/freeswitch//Makefile.am', u'src': u'Makefile.am.extra'})
changed: [freeswitch-mrf-02] => (item={u'dest': u'/usr/local/src/freeswitch//build/modules.conf.in', u'src': u'modules.conf.in.extra'})
changed: [freeswitch-mrf-02] => (item={u'dest': u'/usr/local/src/freeswitch//conf/vanilla/autoload_configs/modules.conf.xml', u'src': u'modules.conf.vanilla.xml.extra'})

However, upon the installation completion the freeswitch log reports the errors during the test call:

7a5ae09c-05c0-11eb-914e-074ba808c07a 2020-10-03 17:36:22.180645 [DEBUG] switch_ivr.c:632 sofia/drachtio_mrf/nobody@192.168.1.115:5060 Command Execute [depth=1] speak(google_tts|en-GB-Wavenet-A|Hi there!  Let's play a game of telephone: you say something and I will repeat back what I heard.  Go ahead..)
7a5ae09c-05c0-11eb-914e-074ba808c07a EXECUTE [depth=1] sofia/drachtio_mrf/nobody@192.168.1.115:5060 speak(google_tts|en-GB-Wavenet-A|Hi there!  Let's play a game of telephone: you say something and I will repeat back what I heard.  Go ahead..)
2020-10-03 17:36:22.180645 [ERR] switch_core_speech.c:62 Invalid speech module [google_tts]!
7a5ae09c-05c0-11eb-914e-074ba808c07a 2020-10-03 17:36:22.180645 [ERR] switch_ivr_play_say.c:3006 Invalid TTS module google_tts[en-GB-Wavenet-A]!

**Comment by davehorton** [comment]
have you set the environment variable GOOGLE_APPLICATION_CREDENTIALS to the path of the file containing your google credentials?

What happens if you execute the following

```
sudo /usr/local/freeswitch/bin/fs_cli -x "reload mod_google_tts"
```

**Comment by yuri2000** [comment]
Yes, Dave, that environment variable has been set.

This is the output in the server:

root@freeswitch-mrf-01:~# fs_cli -x "reload mod_google_tts"
+OK Reloading XML
-ERR unloading module [No such module!]
-ERR loading module [module load file routine returned an error]

root@freeswitch-mrf-01:~# locate mod_google_tts
/usr/local/src/drachtio-freeswitch-modules/modules/mod_google_tts
/usr/local/src/drachtio-freeswitch-modules/modules/mod_google_tts/LICENSE
/usr/local/src/drachtio-freeswitch-modules/modules/mod_google_tts/Makefile.am
/usr/local/src/drachtio-freeswitch-modules/modules/mod_google_tts/README.md
/usr/local/src/drachtio-freeswitch-modules/modules/mod_google_tts/conf
/usr/local/src/drachtio-freeswitch-modules/modules/mod_google_tts/google_glue.cpp
/usr/local/src/drachtio-freeswitch-modules/modules/mod_google_tts/google_glue.h
/usr/local/src/drachtio-freeswitch-modules/modules/mod_google_tts/mod_google_tts
/usr/local/src/drachtio-freeswitch-modules/modules/mod_google_tts/mod_google_tts.c
/usr/local/src/drachtio-freeswitch-modules/modules/mod_google_tts/mod_google_tts.h
/usr/local/src/drachtio-freeswitch-modules/modules/mod_google_tts/conf/autoload_configs
/usr/local/src/drachtio-freeswitch-modules/modules/mod_google_tts/conf/autoload_configs/google_tts.xml
/usr/local/src/freeswitch/src/mod/applications/mod_google_tts
/usr/local/src/freeswitch/src/mod/applications/mod_google_tts/.deps
/usr/local/src/freeswitch/src/mod/applications/mod_google_tts/LICENSE
/usr/local/src/freeswitch/src/mod/applications/mod_google_tts/Makefile
/usr/local/src/freeswitch/src/mod/applications/mod_google_tts/Makefile.am
/usr/local/src/freeswitch/src/mod/applications/mod_google_tts/Makefile.in
/usr/local/src/freeswitch/src/mod/applications/mod_google_tts/README.md
/usr/local/src/freeswitch/src/mod/applications/mod_google_tts/conf
/usr/local/src/freeswitch/src/mod/applications/mod_google_tts/google_glue.cpp
/usr/local/src/freeswitch/src/mod/applications/mod_google_tts/google_glue.h
/usr/local/src/freeswitch/src/mod/applications/mod_google_tts/mod_google_tts
/usr/local/src/freeswitch/src/mod/applications/mod_google_tts/mod_google_tts.c
/usr/local/src/freeswitch/src/mod/applications/mod_google_tts/mod_google_tts.h
/usr/local/src/freeswitch/src/mod/applications/mod_google_tts/.deps/mod_google_tts_la-google_glue.Plo
/usr/local/src/freeswitch/src/mod/applications/mod_google_tts/.deps/mod_google_tts_la-mod_google_tts.Plo
/usr/local/src/freeswitch/src/mod/applications/mod_google_tts/conf/autoload_configs
/usr/local/src/freeswitch/src/mod/applications/mod_google_tts/conf/autoload_configs/google_tts.xml


However, mod_google_tts.so is not found
So, it was not compiled.

**Comment by davehorton** [comment]
I am guessing the issue is that you need to update your playbook to change the relevant variable name from `build_with_grpc` to `build_with_extra`.  This change was made to reflect the fact that with the addition of aws transcription the extra modules are not purely grpc-based.

Here is the example playbook I used to successfully install the modules:
```
---
- hosts: all
  become: yes
  vars_prompt:
    - name: "build_with_extra"
      prompt: "Include the extra modules (mod_aws_transcribe, mod_google_transcribe, mod_google_tts, mod_dialogflow)?"
      private: no
      default: false
    - name: "cloud_provider"
      prompt: "Cloud provider: aws, gcp, azure, digital_ocean"
      private: no
      default: none

  roles:
    - ansible-role-fsmrf
```

**Comment by yuri2000** [comment]
Many thanks, Dave! It's fine now.
